// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "MyCameraApp",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "MyCameraApp",
            targets: ["AppModule"],
            bundleIdentifier: "Fajar Wrazdi",
            teamIdentifier: "8YKR56963U",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .binoculars),
            accentColor: .presetColor(.teal),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .landscapeRight
            ],
            capabilities: [
                .fileAccess(.userSelectedFiles, mode: .readWrite),
                .fileAccess(.pictureFolder, mode: .readWrite),
                .microphone(purposeString: "Trial app"),
                .photoLibrary(purposeString: "Trial app"),
                .camera(purposeString: "Trial app")
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
